apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-web-app-youtuber
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: naga228/image26:latest  # Replace with your image name and tag
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: maven-web-app-youtuber
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Define a specific NodePort (range 30000-32767 for Kubernetes)
  type: NodePort
